config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users
  devise_scope :user do
    get ':user/profile', to: 'devise/registrations#edit', as: :edit_user_profile
  end
  use_doorkeeper

  resources :routes
  resources :buses
  resources :trips
  resources :boarding_points

  mount Api => '/'

  get 'search', to: 'tickets#index', as: 'search'
  get 'book_seats/:id', to: 'tickets#book_seats', as: 'book_seats'
  post 'payment', to: 'tickets#payment', as: 'payment'
  get 'process_payment', to: 'tickets#process_payment'
  post 'confirm_payment', to: 'tickets#confirm_payment'
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
end

app/models/boarding_point.rb
class BoardingPoint < ApplicationRecord
  include Resources
  include WhitespaceValidation

  has_many :boardings, dependent: :nullify
  has_many :trips, through: :boardings

  validates :name, presence: true, format: { with: VALID_LOCATION_REGEX }
  validates :name, uniqueness: { case_sensitive: false }
end

app/controllers/boarding_points_controller.rb
class BoardingPointsController < ApplicationController
  load_and_authorize_resource
  before_action :find_boarding_point_by_id, only: %i[edit update destroy]

  def index
    @boarding_points = BoardingPoint.all.order(sort_column)
  end

  def new
    @boarding_point = BoardingPoint.new
  end

  def edit; end

  def create
    @boarding_point = BoardingPoint.new(boarding_point_params)

    if @boarding_point.save
      redirect_to action: 'index', status: :created
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @boarding_point.update(boarding_point_params)
      redirect_to action: 'index', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @boarding_point.destroy
    redirect_to action: 'index', status: :see_other
  end

  private

  def sort_column
    default_column = 'id'
    default_direction = 'asc'

    sortable_columns = ['id', 'name']
    sortable_directions = %w[asc desc]

    sort_column = params[:sort_column].in?(sortable_columns) ? params[:sort_column] : default_column

    sort_direction = if params[:sort_direction].in?(sortable_directions)
                       params[:sort_direction]
                     else
                       default_direction
                     end

    "#{sort_column} #{sort_direction}"
  end

  def boarding_point_params
    params.require(:boarding_point).permit(:name)
  end

  def find_boarding_point_by_id
    @boarding_point = BoardingPoint.find_by(id: params[:id])

    return if @boarding_point

    flash[:alert] = I18n.t('not_found.boarding_point_not_found')
    redirect_to action: 'index'
  end
end

app/views/boarding_points/_form.html.erb
<%= form_with model: @boarding_point do |form| %>
  <% if @boarding_point.errors.any? %>
    <div class="card notification is-danger">
      <h2><%= pluralize(@boarding_point.errors.count, "error") %> prohibited this Boarding Point from being saved:</h2>
      <ul>
        <% @boarding_point.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %><br>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boarding_points/edit.html.erb
<h1 class="is-size-3">Edit Boarding Point Information</h1>
<%= render 'form', boarding_point: @boarding_point %>

app/views/boarding_points/index.html.erb
<h1 class="is-size-3">All Boarding Points</h1>
<nav>
  <%= link_to "Add Boarding Point", new_boarding_point_path%>
</nav>
<br>
<table border="1" class="table">
  <tr>
    <th><%= sortable_column_header 'ID', 'id' %></th>
    <th><%= sortable_column_header 'Name', 'name' %></th>
    <th colspan=2>Action</th>
  </tr>
  <% for boarding_point in @boarding_points  do%>
    <tr>
      <td><%= boarding_point.id %></td>
      <td><%= boarding_point.name %></td>
      <td><%= link_to "Edit", edit_boarding_point_path(boarding_point) %></td>
      <td><%= link_to "Delete", boarding_point_path(boarding_point),data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }%>
      </td>
    </tr>
  <%end%>
</table>

app/views/boarding_points/new.html.erb
<h1 class="is-size-3">Add Boarding Point Information</h1>
<%= render 'form', boarding_point: @boarding_point %>