config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users
  devise_scope :user do
    get ':user/profile', to: 'devise/registrations#edit', as: :edit_user_profile
  end
  use_doorkeeper

  resources :routes
  resources :buses
  resources :trips
  resources :boarding_points

  mount Api => '/'

  get 'search', to: 'tickets#index', as: 'search'
  get 'book_seats/:id', to: 'tickets#book_seats', as: 'book_seats'
  post 'payment', to: 'tickets#payment', as: 'payment'
  get 'process_payment', to: 'tickets#process_payment'
  post 'confirm_payment', to: 'tickets#confirm_payment'
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
end

app/views/shared/_flash.html.erb
<% if flash[:success] %>
  <div class="card notification is-success">
    <%= flash[:success] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="card notification is-info">
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="card notification is-info">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "BUS TICKETING SYSTEM", root_path, class: "navbar-item is-size-3 has-text-weight-bold" %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
        <% if current_user %>
            <% if current_user.role == 'admin' %>
                <%= link_to "Buses", buses_path, class: "navbar-item" %>
                <%= link_to "Trips", trips_path, class: "navbar-item" %>
                <%= link_to "Routes", routes_path, class: "navbar-item" %>
                <%= link_to "Boarding Points", boarding_points_path, class: "navbar-item" %>
            <% end %>
        <% end %>
        <%= link_to "Book Ticket", search_path, class: "navbar-item" %>

    </div>

    <div class="navbar-end">
        <div class="navbar-item">
                <% if current_user %>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                          <%= current_user.first_name %>
                        </a>

                        <div class="navbar-dropdown">
                        <%= link_to "Dashboard", dashboard_path, class: "navbar-item" %>
                                                    <hr class="navbar-divider">
                        <%= link_to "Update Profile", edit_user_registration_path, class: "navbar-item" %>

                        </div>
                    </div>
                    <div class="buttons">
                        <%= link_to "SignOut", destroy_user_session_path, data:{ "turbo-method": :delete }, class: "button is-light" %>
                    </div>
                <% else %>
                <div class="buttons">
                    <%= link_to 'Sign up', new_user_registration_path, class: "button is-light" %>
                    <%= link_to 'Sign in', new_user_session_path, class: "button is-light" %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
  </div>
</nav>