config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users
  devise_scope :user do
    get ':user/profile', to: 'devise/registrations#edit', as: :edit_user_profile
  end
  use_doorkeeper

  resources :routes
  resources :buses
  resources :trips
  resources :boarding_points

  mount Api => '/'

  get 'search', to: 'tickets#index', as: 'search'
  get 'book_seats/:id', to: 'tickets#book_seats', as: 'book_seats'
  post 'payment', to: 'tickets#payment', as: 'payment'
  get 'process_payment', to: 'tickets#process_payment'
  post 'confirm_payment', to: 'tickets#confirm_payment'
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
end

app/models/route.rb
class Route < ApplicationRecord
  include Resources
  include WhitespaceValidation

  has_many :trips, dependent: :nullify

  validates :source, :destination, presence: true, format: { with: VALID_LOCATION_REGEX }
  validates :source, uniqueness: { scope: :destination }

  def full_name
    "#{source} - #{destination}"
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :find_route_by_id, only: %i[edit update destroy]
  load_and_authorize_resource

  def index
    @routes = Route.all.order(sort_column)
  end

  def new
    @route = Route.new
  end

  def edit; end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to action: 'index', status: :created
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @route.update(route_params)
      redirect_to action: 'index', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @route.destroy
    redirect_to action: 'index', status: :see_other
  end

  private

  def sort_column
    default_column = 'id'
    default_direction = 'asc'

    sortable_columns = ['id', 'source', 'destination']
    sortable_directions = %w[asc desc]

    sort_column = params[:sort_column].in?(sortable_columns) ? params[:sort_column] : default_column

    sort_direction = if params[:sort_direction].in?(sortable_directions)
                       params[:sort_direction]
                     else
                       default_direction
                     end

    "#{sort_column} #{sort_direction}"
  end

  def route_params
    params.require(:route).permit(:source, :destination)
  end

  def find_route_by_id
    @route = Route.find_by(id: params[:id])

    return if @route

    flash[:alert] = I18n.t('not_found.route_not_found')
    redirect_to action: 'index'
  end
end

app/views/routes/_form.html.erb
<%= form_with model: @route do |form| %>
  <% if @route.errors.any? %>
    <div class="card notification is-danger">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this Route from being saved:</h2>
      <ul>
        <% @route.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :source %><br>
    <%= form.text_field :source %>
  </div>
  <div>
    <%= form.label :destination %><br>
    <%= form.text_field :destination %><br>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1 class="is-size-3">Edit Route Information</h1>
<%= render 'form', route: @route %>

app/views/routes/index.html.erb
<h1 class="is-size-3">All Routes</h1>
<nav>
  <%= link_to "Add Route", new_route_path %>
</nav>
<br>
<table border="1"  class="table">
  <tr>
    <th><%= sortable_column_header 'ID', 'id' %></th>
    <th><%= sortable_column_header 'Source', 'source' %></th>
    <th><%= sortable_column_header 'Destination', 'destination' %></th>
    <th colspan=2>Action</th>
  </tr>
  <% for route in @routes  do%>
    <tr>
      <td><%= route.id %></td>
      <td><%= route.source %></td>
      <td><%= route.destination %></td>
      <td><%= link_to "Edit", edit_route_path(route) %></td>
      <td><%= link_to "Delete", route_path(route), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }%>
      </td>
    </tr>
  <%end%>
</table>

app/views/routes/new.html.erb
<h1 class="is-size-3">Add Route Information</h1>
<%= render 'form', route: @route %>