config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  devise_for :users
  devise_scope :user do
    get ':user/profile', to: 'devise/registrations#edit', as: :edit_user_profile
  end
  use_doorkeeper

  resources :routes
  resources :buses
  resources :trips
  resources :boarding_points

  mount Api => '/'

  get 'search', to: 'tickets#index', as: 'search'
  get 'book_seats/:id', to: 'tickets#book_seats', as: 'book_seats'
  post 'payment', to: 'tickets#payment', as: 'payment'
  get 'process_payment', to: 'tickets#process_payment'
  post 'confirm_payment', to: 'tickets#confirm_payment'
  get 'dashboard', to: 'users#dashboard', as: 'dashboard'
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  load_and_authorize_resource
  before_action :find_bus_by_id, only: %i[edit update destroy]

  def index
    @buses = Bus.all.order(sort_column)
  end

  def new
    @bus = Bus.new
  end

  def edit; end

  def create
    @bus = Bus.new(bus_params)
    if @bus.save
      redirect_to action: 'index', status: :created
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bus.update(bus_params)
      redirect_to action: 'index', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @bus.destroy
    redirect_to action: 'index', status: :see_other
  end

  private

  def sort_column
    default_column = 'id'
    default_direction = 'asc'

    sortable_columns = ['id', 'code', 'company', 'bus_type', 'capacity']
    sortable_directions = %w[asc desc]

    sort_column = params[:sort_column].in?(sortable_columns) ? params[:sort_column] : default_column

    sort_direction = if params[:sort_direction].in?(sortable_directions)
                       params[:sort_direction]
                     else
                       default_direction
                     end

    "#{sort_column} #{sort_direction}"
  end
  def bus_params
    params.require(:bus).permit(:code, :bus_type, :company, :capacity)
  end

  def find_bus_by_id
    @bus = Bus.find_by(id: params[:id])
    return if @bus

    flash[:alert] = I18n.t('not_found.bus_not_found')
    redirect_to action: 'index'
  end
end

app/views/buses/_form.html.erb
<%= form_with model: @bus do |form| %>
  <% if @bus.errors.any? %>
    <div class="card notification is-danger">
      <h2><%= pluralize(@bus.errors.count, "error") %> prohibited this Bus from being saved:</h2>
      <ul>
        <% @bus.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :code %><br>
    <%= form.text_field :code %>
  </div>
  <div>
    <%= form.label :company %><br>
    <%= form.text_field :company %><br>
  </div>
  <div>
    <%= form.label :bus_type %><br>
    <%= form.select :bus_type, ['ac','non_ac'] %><br>
  </div>
  <div>
    <%= form.label :capacity %><br>
    <%= form.number_field :capacity %><br>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<h1 class="is-size-3">Edit Bus Information</h1>
<%= render 'form', bus: @bus %>

app/views/buses/index.html.erb
<h1 class="is-size-3">All Buses</h1>
<nav>
  <%= link_to "Add Bus", new_bus_path%>
</nav>
<br>
<table border="1" class="table">
  <tr>
    <th><%= sortable_column_header 'ID', 'id' %></th>
    <th><%= sortable_column_header 'Code', 'code' %></th>
    <th><%= sortable_column_header 'Company', 'company' %></th>
    <th><%= sortable_column_header 'Type', 'bus_type' %></th>
    <th><%= sortable_column_header 'Capacity', 'capacity' %></th>
    <th colspan=2>Action</th>
  </tr>
  <% for bus in @buses  do%>
    <tr>
      <td><%= bus.id %></td>
      <td><%= bus.code %></td>
      <td><%= bus.company %></td>
      <td><%= bus.bus_type %></td>
      <td><%= bus.capacity %></td>
      <td><%= link_to "Edit", edit_bus_path(bus) %></td>
      <td><%= link_to "Delete", bus_path(bus),data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  }%>
      </td>
    </tr>
  <%end%>
</table>

app/views/buses/new.html.erb
<h1  class="is-size-3">Add Bus Information</h1>
<%= render 'form', bus: @bus %>